name: Deploy (dev -> e2e -> prod)

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/dependabot.yml'

jobs:
  deploy_to_dev:
    name: Dev
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/deploy-to-dev.yaml
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
